spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://db:3306/Health?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
    hibernate:
      ddl-auto: validate
    show-sql: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
